### PR TITLE
Add DeepLabCut MyST mini-hackathon blog post

### PR DESCRIPTION
**Pull request by jnywong**
Closes https://github.com/2i2c-org/meta/issues/1416.

### CODE REVIEW

**Comment by jnywong** [comment]
Hey @choldgraf ! Throwing this over to you for a review since you were mostly involved in this work 😄

**Review by choldgraf — APPROVED** [review]
I think it looks great, thanks for this write-up @jnywong 

I'll plan to merge this tomorrow California time. In the meantime, maybe @AlexEMG
 or @MMathisLab want to share thoughts or suggestions?

**Comment by MMathisLab** [comment]
this looks great, thanks so much for the shout out! 💜

**Comment by choldgraf** [comment]
woo - thanks for the <3 @MMathisLab :-D 

@jnywong I've merged and it'll now go live - let me know when you post on social media and I can signal boost

**Pull request merged**
