### PR TITLE
Donate button

### PR DESCRIPTION
**Pull request by choldgraf**
This adds a "donate" button to the 2i2c website. It currently points a `mailto` to `hello@2i2c.org`. Not super sophisticated, but I figure if we're gonna be a non-profit, we should be asking for donations! Scott S also mentioned that ICSI should have no problem accepting donations (though they'd take their indirect cost rate on any that come in).

What do folks think? Am I jumping the gun here?

**Do not merge** until we figure out a donation strategy with ICSI

### CODE REVIEW

**Comment by yuvipanda** [comment]
mmmmm small donations mmmm. I LOVE DIRECT FUNDING FROM USERS

**Comment by choldgraf** [comment]
I wonder if [opencollective](https://opencollective.com/pricing) could be a way for us to work out a donation plan with ICSI, depending on whether they're interested.

**Comment by yuvipanda** [comment]
How do we find out if ICSI is interested?

Also what would we be directing the donations to?

**Comment by choldgraf** [comment]
We need to ask Lea I think, and good question about the account, right now ICSI manages all of our accounts so that’s why I assume we’d try to run something through them (depending on what we’d use this money for, but if we wanna, say, pay people with these small donations, we’ll need an administration to actually do that, and right now that’s ICSI.

**Comment by choldgraf** [comment]
### 2021-10-18

I spoke with the CS&S team and they already have a donation service set up for their projects via DonorBox. They sent me the HTML to get this working, and I've added it to this site!

I think that this PR is now ready for review and/or merge.

Check out the updated donation section here: https://deploy-preview-25--cocky-booth-e7ed17.netlify.app/#donate

Since CS&S requests that we use this pattern for donations, I don't think that it's something we need to discuss or decide on much. I also don't think it's controversial that we accept donations at all, since they are no-strings-attached. I'll **plan to merge this on Tuesday unless there are objections**.

**Comment by yuvipanda** [comment]
OH MY GOD I AM SO EXCITED I WANT TO PUSH THE MERGE BUTTON BUT I WILL WAIT AND LET YOU DO IT

**Comment by choldgraf** [comment]
wohooo - let there be donate button!

**Pull request merged**
