### PR TITLE
Change Yuvi's title

### PR DESCRIPTION
**Pull request by yuvipanda**
I think this matches what I *want* to do much more so than
a 'Director' title. My understanding of this primarily comes
from my wikimedia experience - some information on what
that title means comes from
https://www.mediawiki.org/wiki/Wikimedia_Engineering/Careers#Principal_%5BSoftware/Operations%5D_Engineer

https://study.com/articles/difference_between_senior_principle_engineer.html
also has some useful information. Ultimately, however,
https://www.kitchensoap.com/2012/10/25/on-being-a-senior-engineer/
is the guiding light. 

https://github.com/2i2c-org/team-compass/pull/255 adds what the responsibilities
of this title are.

### CODE REVIEW

**Comment by damianavila** [comment]
I would defer the approval to @choldgraf for obvious reasons but 👍  on @yuvipanda's request on this PR.

**Comment by choldgraf** [comment]
I think this sounds good to me - especially if it makes @yuvipanda more comfortable about his responsibilities and expectations. I chatted briefly with @yuvipanda about this and he said he'd also be willing to update the description of this title here: https://team-compass.2i2c.org/en/latest/positions.html#director-of-engineering so that we have a definition of what "Principal Engineer" means

**Comment by choldgraf** [comment]
Just a quick update on this one - @yuvipanda and I had a conversation about this, and we're going to brainstorm a joint list of "responsibilities and expectations" for a "Senior open infrastructure engineer" role to make sure that this is explicitly defined (and also not just special-cased for Yuvi).

**Comment by yuvipanda** [comment]
I opened https://github.com/2i2c-org/team-compass/pull/255, @choldgraf :)

**Comment by choldgraf** [comment]
Now that https://github.com/2i2c-org/team-compass/pull/255 is merged, I think that we can merge this one as well! Thanks @yuvipanda for so much thoughtfulness and conversation about this :-)

**Pull request merged**
